server:
  port: 5555
spring:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/building_market
    username: postgres
    password: postgres
